name: remote ssh command
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       repository: Piotr-Dziekonski/dziekonbot
       token: ${{ secrets.ACCESS_TOKEN }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ -d Projects/ ];
          then cd Projects;
          else mkdir Projects;
          cd Projects;
          fi;
          if [ -d dziekonbot/ ];
          then cd dziekonbot;
          git stash;
          git fetch https://${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/Piotr-Dziekonski/dziekonbot.git;
          git pull https://${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/Piotr-Dziekonski/dziekonbot.git;    
          else git clone https://${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/Piotr-Dziekonski/dziekonbot.git
          cd dziekonbot;
          fi
          npm install
          docker build --tag dziekonbot .
          docker stop dziekonbot
          docker rm dziekonbot
          docker run --detach --name dziekonbot dziekonbot:latest
          
